# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: github-issue-bot Deployment

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - name: Git checkout
        uses: actions/checkout@v2
      - name: SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_DEPLOY_KEY }}
      - name: Deploy to VPS
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete
          path: .
          remote_path: /var/github-issue-bot
          remote_host: ${{ secrets.VPS_DEPLOY_ADDRESS }}
          remote_port: ${{ secrets.VPS_DEPLOY_PORT }}
          remote_user: ${{ secrets.VPS_DEPLOY_USER }}
          remote_key: ${{ secrets.VPS_DEPLOY_KEY }}
      - name: Update Blog Source Posts on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_DEPLOY_ADDRESS }}
          username: ${{ secrets.VPS_DEPLOY_USER }}
          key: ${{ secrets.VPS_DEPLOY_KEY }}
          port: ${{ secrets.VPS_DEPLOY_PORT }}
          script: |
            cd /var/github-issue-bot
            npm i
      - name: Notify
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            github-issue-bot deployed.
          format: markdown
