# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: github-issue-bot Deployment

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Deploy VPS
        run: |
          rsync -az -vv --delete -e 'ssh -p ${{ secrets.VPS_DEPLOY_KEY }}' ./ ${{ secrets.VPS_DEPLOY_USER }}@${{ secrets.VPS_DEPLOY_ADDRESS }}:/var/github-issue-bot
      - name: Update Blog Source Posts on VPS
        uses: appleboy/ssh-action@master
        with:
          host: 1991421.cn
          username: root
          key: ${{ secrets.VPS_DEPLOY_KEY }}
          port: ${{ secrets.VPS_DEPLOY_PORT }}
          script: |
            cd /var/github-issue-bot
            npm i
      - name: Notify
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            github-issue-bot deployed.
          format: markdown
