# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: github-issue-bot Deployment

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.VPS_DEPLOY_KEY }}
          known_hosts: ${{ secrets.VPS_DEPLOY_ADDRESS }}
          if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
      - name: Deploy VPS
        run: |
          ssh-keyscan -H ${{ secrets.VPS_DEPLOY_ADDRESS }} >> ~/.ssh/known_hosts
          rsync -a . ${{ secrets.VPS_DEPLOY_USER }}@${{ secrets.VPS_DEPLOY_ADDRESS }}:/home/opc/github-issue-bot
      - name: Update Bot Program on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_DEPLOY_ADDRESS }}
          username: ${{ secrets.VPS_DEPLOY_USER }}
          key: ${{ secrets.VPS_DEPLOY_KEY }}
          port: ${{ secrets.VPS_DEPLOY_PORT }}
          script: |
            cd /home/opc/github-issue-bot
            npm i
            pm2 restart github-issue-bot
      - name: Notify
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            github-issue-bot deployed.
          format: markdown
